export type GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export type GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";




// export type GET_CART_REQUEST = "GET_CART_REQUEST";
// export type GET_CART_SUCCESS = "GET_CART_SUCCESS";
export type OPEN_CART = "OPEN_CART";
export type CLOSE_CART = "CLOSE_CART";
export type INCREASE_CART_ITEM = "INCREASE_CART_ITEM";
export type DECREASE_CART_ITEM = "DECREASE_CART_ITEM";
export type REMOVE_FROM_CART = "REMOVE_FROM_CART";
